site_name: Žitná Apartment
site_author: kesano.cz

theme:
  name: material
  logo: public/logo.png
  favicon: public/favicon.ico
  language: en
  palette:
    - scheme: default
      primary: white
      accent: custom
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\u200b\-\.,!=\[\]()"`/]+'
  - minify:
      minify_html: true
  - with-pdf:
      author: Žitná 564/14, 120 00 Nové Město
      output_path: public/guide.pdf
      copyright: "-"
      cover_title: "Žitná Apartment 117"
      cover_subtitle:
        "Enjoy a stay in a modern apartment in the very center of Prague."
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
#        - locale: de
#          name: Deutsch
#          build: true
#          nav_translations:
#            Welcome to Our Apartment: Willkommen in unserer Wohnung
#            Transportation: Transport
nav:
  - Welcome to Our Apartment: index.md
  - House Rules: house-rules.md
  - Transportation: transportation.md
  - Apartment Guide: apartment-guide.md
  - Money: money.md

extra:
  generator: false
