site_name: Žitná Apartment
site_author: kesano.cz

theme:
  name: material
  logo: public/logo.png
  favicon: public/favicon.ico
  language: en
  palette:
    - scheme: default
      primary: white
      accent: custom
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\u200b\-\.,!=\[\]()"`/]+'
  - minify:
      minify_html: true
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
          nav_translations:
            Welcome to Our Apartment: Willkommen in unserer Wohnung
            Before You Arrive: Vor Ihrer Ankunft
nav:
  - Welcome to Our Apartment: index.md
  - Before You Arrive: before-you-arrive.md

extra:
  generator: false
